// Auto-generated
let project = new Project('BESTGAME');

project.addSources('Sources');
project.addLibrary("E:/Blender/ArmorySDK/armory");
project.addLibrary("E:/Blender/ArmorySDK/iron");
project.addLibrary("E:/Blender/ArmorySDK/lib/haxebullet");
project.addAssets("E:/Blender/ArmorySDK/lib/haxebullet/ammo/ammo.wasm.js", { notinlist: true });
project.addAssets("E:/Blender/ArmorySDK/lib/haxebullet/ammo/ammo.wasm.wasm", { notinlist: true });
project.addParameter('arm.Inventory');
project.addParameter("--macro keep('arm.Inventory')");
project.addParameter('arm.CharacterAnimation');
project.addParameter("--macro keep('arm.CharacterAnimation')");
project.addParameter('arm.Interactive');
project.addParameter("--macro keep('arm.Interactive')");
project.addParameter('arm.Sight');
project.addParameter("--macro keep('arm.Sight')");
project.addParameter('armory.trait.WalkNavigation');
project.addParameter("--macro keep('armory.trait.WalkNavigation')");
project.addParameter('arm.Movement');
project.addParameter("--macro keep('arm.Movement')");
project.addParameter('armory.trait.physics.bullet.PhysicsWorld');
project.addParameter("--macro keep('armory.trait.physics.bullet.PhysicsWorld')");
project.addParameter('armory.trait.physics.bullet.RigidBody');
project.addParameter("--macro keep('armory.trait.physics.bullet.RigidBody')");
project.addShaders("build_game/compiled/Shaders/*.glsl", { noembed: false});
project.addShaders("build_game/compiled/Hlsl/*.glsl", { noprocessing: true, noembed: false });
project.addAssets("build_game/compiled/Assets/**", { notinlist: true });
project.addAssets("build_game/compiled/Shaders/*.arm", { notinlist: true });
project.addAssets("Assets/grid.png", { notinlist: true });
project.addAssets("Assets/stoneTexture.png", { notinlist: true });
project.addAssets("E:/Blender/ArmorySDK/armory/Assets/brdf.png", { notinlist: true });
project.addAssets("E:/Blender/ArmorySDK/armory/Assets/smaa_area.png", { notinlist: true });
project.addAssets("E:/Blender/ArmorySDK/armory/Assets/smaa_search.png", { notinlist: true });
project.addLibrary("E:/Blender/ArmorySDK/lib/zui");
project.addAssets("E:/Blender/ArmorySDK/armory/Assets/font_default.ttf", { notinlist: false });
project.addDefine('arm_deferred');
project.addDefine('arm_csm');
project.addDefine('rp_hdr');
project.addDefine('rp_renderer=Deferred');
project.addDefine('rp_shadowmap');
project.addDefine('rp_shadowmap_cascade=1024');
project.addDefine('rp_shadowmap_cube=512');
project.addDefine('rp_background=World');
project.addDefine('rp_render_to_texture');
project.addDefine('rp_compositornodes');
project.addDefine('rp_antialiasing=SMAA');
project.addDefine('rp_supersampling=1');
project.addDefine('rp_ssgi=SSAO');
project.addDefine('armory');
project.addDefine('arm_audio');
project.addDefine('arm_physics');
project.addDefine('arm_bullet');
project.addDefine('arm_noembed');
project.addDefine('arm_soundcompress');
project.addDefine('arm_ui');
project.addDefine('arm_skin');
project.addDefine('arm_particles');
project.addAssets("E:/Blender/Projects/game/Assets/**", { notinlist: true });

resolve(project);
